// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBQTgPwDB-ShdZGKHAD_PjpNwV-eoDbLA',
    appId: '1:947064391330:web:ab0c671108df6f9838f9fb',
    messagingSenderId: '947064391330',
    projectId: 'myloginapp-9a40f',
    authDomain: 'myloginapp-9a40f.firebaseapp.com',
    databaseURL: 'https://myloginapp-9a40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapp-9a40f.appspot.com',
    measurementId: 'G-F264XJ0K1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASLA0lwQ8U21rz9-bcoiyJReHkAj_cugk',
    appId: '1:947064391330:android:70e2a986a90ea94138f9fb',
    messagingSenderId: '947064391330',
    projectId: 'myloginapp-9a40f',
    databaseURL: 'https://myloginapp-9a40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapp-9a40f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6z4SbkzzHdd-x-zMT3JVJL3CcPL4yts',
    appId: '1:947064391330:ios:b616cb5d9055b7a038f9fb',
    messagingSenderId: '947064391330',
    projectId: 'myloginapp-9a40f',
    databaseURL: 'https://myloginapp-9a40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapp-9a40f.appspot.com',
    iosBundleId: 'com.example.myprojict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6z4SbkzzHdd-x-zMT3JVJL3CcPL4yts',
    appId: '1:947064391330:ios:b616cb5d9055b7a038f9fb',
    messagingSenderId: '947064391330',
    projectId: 'myloginapp-9a40f',
    databaseURL: 'https://myloginapp-9a40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapp-9a40f.appspot.com',
    iosBundleId: 'com.example.myprojict',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBQTgPwDB-ShdZGKHAD_PjpNwV-eoDbLA',
    appId: '1:947064391330:web:84192c065611b16b38f9fb',
    messagingSenderId: '947064391330',
    projectId: 'myloginapp-9a40f',
    authDomain: 'myloginapp-9a40f.firebaseapp.com',
    databaseURL: 'https://myloginapp-9a40f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myloginapp-9a40f.appspot.com',
    measurementId: 'G-2WS7DVY4MJ',
  );
}
